# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/",
        root,
        returning = porcelain::porcelain_returning_json("root"),
        validate = validate)
    },
    "POST /validate" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/validate",
        model_validate,
        porcelain::porcelain_input_body_json("data", "validate_request"),
        returning = porcelain::porcelain_returning_json("validate_response"),
        validate = validate)
    },
    "POST /compile" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/compile",
        model_compile,
        porcelain::porcelain_input_query(pretty = "logical"),
        porcelain::porcelain_input_body_json("data", "compile_request"),
        returning = porcelain::porcelain_returning_json("compile_response"),
        validate = validate)
    },
    "GET /support/runner-ode" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/support/runner-ode",
        support_runner_ode,
        returning = porcelain::porcelain_returning_json(),
        validate = validate)
    },
    "GET /support/runner-discrete" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/support/runner-discrete",
        support_runner_discrete,
        returning = porcelain::porcelain_returning_json(),
        validate = validate)
    })
}
